ServiceType: private
ArtifactSourceType: DockerCompose
ServiceBuildRegion: ap-southeast-1
RepoName: JJGGu/BetterChatGPT
DockerComposeEnvPath: .env.example
RegionId: ap-southeast-1
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
Owner: JJGGu
Branch: main
Platform: github
