Owner: JJGGu
Platform: github
ServiceType: private
Branch: main
AllowedRegions:
- ap-southeast-1
ArtifactSourceType: DockerCompose
RepoName: JJGGu/BetterChatGPT
DockerComposeEnvPath: .env.example
RegionId: cn-hangzhou
CustomParameters: ''
DockerComposeYamlPath: docker-compose.yml
